### ISSUE TITLE
AES-GCM import key not working

### ISSUE THREAD

**Issue by sirpy** [kevlened/msrCrypto#9]
The following works on browser webcrypto but not when using msrcrypto, it throws an error with message about "keyData". I've tested both in browser and in expo react native in both it throws the same error.
```
try {
    await crypto.subtle.importKey(
      "raw",
      new Uint8Array([1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1]),
      "AES-GCM",
      false,
      ["encrypt", "decrypt"]
    );
  } catch (e) {
    console.log(e.message);
  }
```

The error from expo
```
[Unhandled promise rejection: Error: keyData]
- node_modules/msrcrypto/dist/msrcrypto.js:9130:28 in buildParameterCollection
- node_modules/msrcrypto/dist/msrcrypto.js:9174:38 in executeOperation
- ... 12 more stack frames from framework internals
```

**Comment by kevlened** [comment]
Currently `msrcrypto` only works with `jwk`s

**Comment by kevlened** [comment]
This should be resolved by https://github.com/kevlened/msrCrypto/commit/07e3364122557224db96bd0d5c0b4f4c351963c5 which is included in `msrcrypto@1.5.6` and `isomorphic-webcrypto@2.2.3`

**Comment by AJLoveChina** [comment]
oh my god, ......

I tried so hard, you tell me just jwk....

raw data key not supported to import ?It's too disappointed

**Comment by AJLoveChina** [comment]
> oh my god, ......
> 
> I tried so hard, you tell me just jwk....
> 
> raw data key not supported to import ?It's too disappointed

Sorry , I am going wrong, because I use the file `rootDir/msrcrypto.js`,

instead, `rootDir/dist/msrcrypto.js` is working for `raw data key` import.

Thank you.
